CREATE TABLE HREEMAN.MEMBER
(
    MEMBER_NO           NUMBER,
    MEMBER_EMAIL        VARCHAR2(30),
    MEMBER_PASSWORD     VARCHAR2(16) NOT NULL,
    MEMBER_NAME         VARCHAR2(30) NOT NULL,
    MEMBER_BIRTH        CHAR(8) NOT NULL,
    MEMBER_GENDER       CHAR(1) NOT NULL,
    MEMBER_PHONE_NUMBER VARCHAR2(11),
    MEMBER_REG_DATE     TIMESTAMP(6),
    MEMBER_LOGIN_DATE   TIMESTAMP(6),
    CHECK (MEMBER_GENDER IN ('M', 'F'))
)
TABLESPACE HREEMAN_TABLE_SPACE
NOCOMPRESS;

ALTER TABLE HREEMAN.MEMBER
ADD PRIMARY KEY (MEMBER_NO);

ALTER TABLE HREEMAN.MEMBER
ADD UNIQUE (MEMBER_EMAIL);

COMMENT ON TABLE HREEMAN.MEMBER IS '사용자정보';
COMMENT ON COLUMN HREEMAN.MEMBER.MEMBER_NO IS '사용자 번호';
COMMENT ON COLUMN HREEMAN.MEMBER.MEMBER_EMAIL IS '사용자 이메일';
COMMENT ON COLUMN HREEMAN.MEMBER.MEMBER_PASSWORD IS '사용자 암호';
COMMENT ON COLUMN HREEMAN.MEMBER.MEMBER_NAME IS '사용자 이름';
COMMENT ON COLUMN HREEMAN.MEMBER.MEMBER_BIRTH IS '사용자 생년월일(YYYYMMDD)';
COMMENT ON COLUMN HREEMAN.MEMBER.MEMBER_GENDER IS '사용자 성별(M:남자, F:여자)';
COMMENT ON COLUMN HREEMAN.MEMBER.MEMBER_PHONE_NUMBER IS '사용자 핸드폰 번호';
COMMENT ON COLUMN HREEMAN.MEMBER.MEMBER_REG_DATE IS '사용자 가입 일자';
COMMENT ON COLUMN HREEMAN.MEMBER.MEMBER_LOGIN_DATE IS '사용자 최종 로그인 시간';

CREATE SEQUENCE HREEMAN.SEQ_MEMBER_NO
START WITH 0
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999
NOCACHE;